### ISSUE TITLE
Is OFL better than GPL?

### ISSUE THREAD

**Issue by igauravsehrawat** [Holger-Will/code-128-font#1]
Hi,
Just would like to have your opinion if font repo should have [Open Font License.]?(https://en.wikipedia.org/wiki/SIL_Open_Font_License)

Thanks

**Comment by Holger-Will** [comment]
I have no opinion about that. If you prefer i can change it to OFL...

**Comment by igauravsehrawat** [comment]
I think it would nice to say same license as this [Google Font](https://github.com/graphicore/librebarcode), may be you can submit this font and similar fonts on Google Fonts too.

Thanks

**Comment by pennersr** [comment]
@Holger-Will  Please do change to OFL. With a GPL font any document embedding the font would be subject to the GPL as well (unless you add the font exception clause). I don't think that this is intentional.

As for the OFL, I think the most relevant part is this:  "The License permits covered fonts to be freely embedded in documents under any terms, but it requires that fonts be packaged with software if they are sold."

**Comment by pennersr** [comment]
@Holger-Will  Come to think of it, the fonts are actually generated using this project: https://github.com/Holger-Will/barcode-font-generator.  Given that anybody is free to re-create the fonts themselves using the generator, I am wondering what the point is in putting a restrictive license on these fonts at all. While these self generated fonts are generated using a GPL based tool, the GPL does not automatically apply to files rolling out of the tool. So basically anybody is free to put whatever license he sees fit on those fonts.

**Comment by Holger-Will** [comment]
sorry... this was a really long wait... i was stuffed with other work. finally switch to OFL!

**Comment by igauravsehrawat** [comment]
Better late than never. (Ahh, Cliche).
Thanks.
